name: Lint Debug

on:
  workflow_dispatch:

jobs:

  lint:
    name: Linting Debug Variant

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Make Gradle executable
        uses: chmod +x ./gradlew

      - name: Execute Gradle - lintDebug
        uses: ./gradlew lintDebug
